clock_format = ""
color_theme = "orange"
cpu_single_graph = true
disable_presets = "All"
gpu_mirror_graph = false
mem_graphs = false
proc_cpu_graphs = false
proc_gradient = false
proc_left = true
proc_sorting = "memory"
rounded_corners = false
save_config_on_exit = false
show_battery = false
show_cpu_watts = false
show_disks = false
show_gpu_info = "Off"
show_io_stat = false
show_uptime = false
shown_boxes = "cpu mem proc"
swap_disk = false
theme_background = false
update_ms = 500
