#!/usr/bin/env sh

symlink() {
  from="$(pwd)/$1"
  to="$HOME/$2"

  mkdir -p "$(dirname "$to")"
  ln -sf "$from" "$to"
}

symlink .config/fish/config.fish .config/fish/config.fish
symlink .config/fontconfig/fonts.conf .config/fontconfig/fonts.conf
symlink .config/foot/foot.ini .config/foot/foot.ini
symlink .config/git/config .config/git/config
symlink .config/lazygit/config.yml .config/lazygit/config.yml
symlink .config/zed/keymap.json .config/zed/keymap.json
symlink .config/zed/settings.json .config/zed/settings.json
