#!/usr/bin/env fish

function symlink
    set from (pwd)/$argv[1]
    set to $HOME/$argv[2]

    mkdir --parents (dirname $to)
    ln --force --symbolic $from $to
end

symlink configuration/alacritty/alacritty.toml .config/alacritty/alacritty.toml
symlink configuration/brave-flags.conf .config/brave-flags.conf
symlink configuration/environment.d/environment.conf .config/environment.d/environment.conf
symlink configuration/fish/config.fish .config/fish/config.fish
symlink configuration/fontconfig/fonts.conf .config/fontconfig/fonts.conf
symlink configuration/git/config .config/git/config
symlink configuration/konsolerc .config/konsolerc
symlink configuration/lazygit/config.yml .config/lazygit/config.yml
symlink configuration/npm/npmrc .config/npm/npmrc
symlink configuration/opencode/opencode.jsonc .config/opencode/opencode.jsonc
symlink configuration/opencode/tui.jsonc .config/opencode/tui.jsonc
symlink configuration/zed/keymap.json .config/zed/keymap.json
symlink configuration/zed/settings.json .config/zed/settings.json
symlink data/konsole/Default.colorscheme .local/share/konsole/Default.colorscheme
symlink data/konsole/Default.profile .local/share/konsole/Default.profile
