#!/usr/bin/env sh

symlink() {
  from="$(pwd)/$1"
  to="$HOME/$2"

  mkdir --parents "$(dirname "$to")"
  ln --force --symbolic "$from" "$to"
}

symlink configuration/fish/config.fish .config/fish/config.fish
symlink configuration/foot/foot.ini .config/foot/foot.ini
symlink configuration/git/config .config/git/config
symlink configuration/lazygit/config.yml .config/lazygit/config.yml
symlink configuration/zed/keymap.json .var/app/dev.zed.Zed/config/zed/keymap.json
symlink configuration/zed/settings.json .var/app/dev.zed.Zed/config/zed/settings.json
