git:
  disableForcePushing: true
  overrideGpg: true
  pagers:
    - pager: /usr/share/git-core/contrib/diff-highlight
gui:
  authorColors:
    "*": yellow
  showCommandLog: false
  useHunkModeInStagingView: false
