git:
  diffRenderers:
    - command: /usr/share/git/diff-highlight/diff-highlight
  disableForcePushing: true
  overrideGpg: true
gui:
  authorColors:
    "*": yellow
  showCommandLog: false
  useHunkModeInStagingView: false
