#!/usr/bin/env fish

if not set --query argv[1]
    echo "Usage: $(status basename) [path]"
    exit 0
end

exiftool \
    -all= \
    -api largefilesupport=1 \
    -overwrite_original \
    -progress \
    -recurse \
    "$argv[1]"
