#!/usr/bin/env fish

set script_name (status filename | path basename)

if not set --query argv[1]
    echo "Usage: $script_name [path]"
    exit 0
end

exiftool \
    -all= \
    -api largefilesupport=1 \
    -overwrite_original \
    -progress \
    -recurse \
    "$argv[1]"
