#!/usr/bin/env fish

if not set --query argv[1]
    echo "Usage: $(status basename) [file_names]"
    exit 0
end

for file_name in $argv
    cjxl \
        --effort 10 \
        --lossless_jpeg 1 \
        --quality 100 \
        "$file_name" \
        (path change-extension ".jxl" "$file_name") \
        && rm "$file_name"
end
