#!/usr/bin/env fish

set distrobox_containers (docker ps --all --filter label=manager=distrobox --quiet)

for container in (docker ps --quiet)
    if not contains $container $distrobox_containers
        docker stop $container
    end
end

docker system prune --all --filter label!=manager=distrobox --force --volumes
