#!/usr/bin/env fish

for container in (docker ps --quiet --filter label=manager!=distrobox)
    docker stop $container
end

docker system prune --all --filter label=manager!=distrobox --force --volumes
