#!/usr/bin/env fish

if not set --query argv[1]
    echo "Usage: $(status basename) [file_paths]"
    exit 0
end

for file_name in $argv
    set flags --best --threads=(nproc)
    if test (path extension "$file_name") = .flac
        set --append flags --force
    else
        set --append flags --delete-input-file
    end
    flac "$file_name" $flags
end
