#!/usr/bin/env fish

if not set --query argv[1]
    echo "Usage: $(status basename) [file_paths]"
    exit 0
end

for file_name in $argv
    wavpack \
        -hh \
        -o (path change-extension ".wv" "$file_name") \
        -x6 \
        "$file_name" \
        && rm "$file_name"
end
