#!/usr/bin/env fish

if not set --query argv[1]
    echo "Usage: $(status basename) [file_paths]"
    exit 0
end

for file_name in $argv
    switch (path extension "$file_name")
        case ".flac"
            flac "$file_name" \
                --best \
                --force \
                --threads=(nproc)
        case "*"
            flac "$file_name" \
                --best \
                --delete-input-file \
                --threads=(nproc)
    end
end
