#!/usr/bin/env fish

sudo systemctl restart docker

set containers (docker ps --quiet)
if test -n "$containers"
    docker stop "$containers"
end

docker system prune --all --force && docker volume prune --all --force
