[colors.bright]
black   = "#636d83"
red     = "#ea858b"
green   = "#aad581"
yellow  = "#ffd885"
blue    = "#85c1ff"
magenta = "#d398eb"
cyan    = "#6ed5de"
white   = "#fafafa"

[colors.normal]
black   = "#282c34"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Regular"

[font.italic]
style = "Regular"

[font]
size = 11.0

[window.dimensions]
columns = 130
lines   = 35

[window.padding]
x = 2
y = 2
